[MQTT]
BROKER_HOST = localhost
BROKER_PORT = 1883
TOPIC_SUB = msh/2/c/#
TOPIC_PUB_ROOT = msh/2/c

[RETICULUM]
# If blank, the app will start, print its hash, and wait.
# Set this to the hash of the remote bridge to enable sending.
REMOTE_DESTINATION_HASH = 

[LOGGING]
# 1 = INFO (Eventos principales), 2 = WARNING/ERROR, 3 = DEBUG (Todo el trafico)
LOG_LEVEL = 1

[AUTOPILOT]
# Si es True, el puente ignora [FILTERING] si detecta conexion de alta velocidad (Ping bajo)
FILTERING_AUTO = True
# Segundos maximos de Ping (RTT) para considerar enlace como rapido. Si es mayor, aplica [FILTERING] estricto.
RTT_CONTINGENCY_SEC = 2.5
# Frecuencia de chequeo de la ruta en segundos
PING_INTERVAL_SEC = 30

[FILTERING]
# Valores "Fallback" (Contingencia). Se usan por defecto y cuando el ping falla o es lento.
ALLOW_ROUTING = False
ALLOW_TELEMETRY = False
ALLOW_UNKNOWN_APPS = False
POSITION_RATE_LIMIT_SEC = 300
NODEINFO_RATE_LIMIT_SEC = 3600
DEDUPLICATION_CACHE_SEC = 600
